### ISSUE TITLE
Possible to construct stronger cache identifier?

### ISSUE THREAD

**Issue by langri-sha** [webpack-contrib/eslint-loader#190]
From what I understand, the current way the cache identifier is [constructed](https://github.com/MoOx/eslint-loader/blob/855cadca02c3e9081eeafe3bfeec610296091c6d/index.js#L157) gives off odd reports if the ESLint configuration has changed between two runs.

I have only one ESLint configuration file, so I could have a straightforward workaround to write a plugin that hooks into the `environment` event from the compiler and maintain a hash for the contents , then manually wipe the cache path assigned to `eslint-loader`, but I'm wondering if this could somehow be managed by the loader itself?

**Comment by MoOx** [comment]
We should probably create a hash with version/config/path and adjust this here https://github.com/MoOx/eslint-loader/blob/667baf33828405b47ba42930ccac0ccaa6546c0b/index.js#L157-L160

**Comment by ricardogobbosouza** [comment]
@langri-sha I'm reviewing the issues
Does this seem to exist now or not? https://github.com/webpack-contrib/eslint-loader/blob/master/index.js#L205
It's been a while! LOL
