### ISSUE TITLE
Confusing about test case eslint-path

### ISSUE THREAD

**Issue by monkingxue** [webpack-contrib/eslint-loader#196]
Hi, I have some problems about test case 1(eslint-path).
I find a mock eslint in mock directory, but I think it's not enough, because the loader also relies on formatter `{formatter: require("eslint/lib/formatters/stylish")}`. If I change eslint path, I want to use the formatter in eslint path instead of the original. But the test case only mock the eslint, I think we also need to mock formatter.

**Comment by ricardogobbosouza** [comment]
Resolve #275

**Comment by ricardogobbosouza** [comment]
@monkingxue 
Resolve #275
