### ISSUE TITLE
Throwing an error for import (code splitting) but using babel-eslint

### ISSUE THREAD

**Issue by appsolutegeek** [webpack-contrib/eslint-loader#208]
Hi,

I get the following error when running webpack.

ERROR in ./src/client/promo.js
Module build failed: SyntaxError: Unexpected token, expected { (2:6)

```
  1 | // Split for vendor
> 2 | import(/* webpackChunkName: "vendor" */ '../vendor');
    |       ^
```
Webstorm was also having the same issue - so I updated the parser in the .eslintrc.js file like so

```
  parser: "babel-eslint",
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 6,
    allowImportExportEverywhere: true
  },
```

And it was fixed BUT eslint-loader continues to throw an issue.

This is my webpack pre command

```
      {
        enforce: 'pre',
        test: /\.js$/,
        include: [
          helpers.root('src', 'client'),
        ],
        exclude: /node_modules/,
        loader: 'eslint-loader'
      },
```

I am at a loss, does anyone know why its not working ??

It seems adding the new parser (babel-eslint) to the .eslintrc.js works for webstorm but eslint-loader doesn't seem to be honouring it.

Thanks in advance

**Comment by bf** [comment]
I have same problem, how did you resolve this issue?

**Comment by evperedadiaz** [comment]
I had a similar error, just that I did not use the "parserOptions" option.
I solved it using the babel plugin "babel-plugin-syntax-dynamic-import".
In my .babelrc file I have the following:

```json
{
  "presets": [
    ["env", {
      "targets": "defaults",
      "useBuiltIns": true
    }]
  ],
  "plugins": ["syntax-dynamic-import"]
}
```
I hope this helps you.

**Comment by SelfishLucho** [comment]
I'm facing the same issue with **Version: webpack 4.29.0** and **"version": "2.1.2"**.
Getting:

> Parsing error: 'import' and 'export' may only appear at the top level

**Comment by ricardogobbosouza** [comment]
@appsolutegeek 
I can not reproduce
Could you provide an example repository?
