### ISSUE TITLE
Cache doesn't bust when .eslintrc changes

### ISSUE THREAD

**Issue by swrobel** [webpack-contrib/eslint-loader#214]
If I have a failure, then change eslintrc to change the rule, then run eslint, it comes up clean, however webpack keeps complaining until I `rm node_modules/.cache/eslint-loader/`

**Comment by hellochicken** [comment]
I did meet this problem, and it took me two days to find this problem!

**Comment by langri-sha** [comment]
Related to #190.

**Comment by mati-o** [comment]
I have the same issue but I can suggest a temp workaround. I did some digging in the source to find the [following code](https://github.com/webpack-contrib/eslint-loader/blob/master/index.js#L169) that builds the `cacheIdentifier` from it's `pkg.version` and the `eslint`'s version
```javascript
var config = assign(
    // loader defaults
    {
      formatter: formatter,
      cacheIdentifier: JSON.stringify({
        "eslint-loader": pkg.version,
        eslint: require(userEslintPath || "eslint").version,
      }),
      eslintPath: "eslint",
    },
    userOptions
  )
```


Apparently, we can provide our own `cacheIdentifier` via the loader options. So I was thinking, why not providing my own `cacheIdentifier` to bust the cache? 

I have used the last modified time of my `.eslintrc` file. I know it's probably not the best way to identify it and I am pretty sure I'll remove it soon once I stabilize my config, but it helps to workaround this issue. I am providing an excerpt from my webpack (4) configuration file. time stamps can change without actual content modification though, but it's okay for me now.

```javascript
// Get the file last modified time to use as a cache identifier
const eslintCacheIdentifier = JSON.stringify(fs.statSync(PATH_TO_ESLINT_RC).mtimeMs);

module.exports = {
  module: {
    // ...
    rules: [
      // ...
      {
        test: /\.(js|jsx)$/,
        enforce: 'pre',
        use: {
          loader: 'eslint-loader',
          options: {
            cache: true,
            cacheIdentifer: eslintCacheIdentifier,
          },
        },
      },
      // ...
    ],
  },
}
}

```

If someone will suggest a better cache identifier or a different suggestion on how to fix this, I may PR. I am wondering, maybe the solution would be to hash the `eslintrc` and use it as the `cacheIdentifier`

**Comment by igimanaloto** [comment]
Encountered this problem today! @mati-o's comment really helped!

**Comment by jenssogaard** [comment]
This really messed my morning up 😆 I guess a manual procedure would be:
`rm -rf node_modules/.cache/eslint-loader`

**Comment by thasmo** [comment]
FYI, this also is the case using `prettier` via `eslint-plugin-prettier` after changing the `.prettierrc` configuration file; the change in the `.prettierrc` file does not invalidate the `eslint-loader` cache.

**Comment by ricardogobbosouza** [comment]
This would require creating a plugin that removes the cache before.
At the moment I recommend removing manually as said @jenssogaard

**Comment by ricardogobbosouza** [comment]
Hi @swrobel 
Try to use [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)
We are building this plugin to have more control than the loader.
With this plugin the cache used is directly from eslint

**Comment by ksjogo** [comment]
Just did run into this. Hashing the eslintrc config might no be enough if that config is extending other configs (we are having a company wide eslint-config-*).

**Comment by ricardogobbosouza** [comment]
Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.
