### ISSUE TITLE
Documentation change - failOnWarning (default: false)

### ISSUE THREAD

**Issue by ivandoric** [webpack-contrib/eslint-loader#223]
Documentation says that the default for `failOnWarning` is `false`, but I guess it's actually `true`. Because it fails on warning for me and Webpack doesn't compile.

But when I explicitly set it to false then it works.

```
{
      loader: 'eslint-loader',
      options: {
             failOnWarning: false
       }
}
```

So either documentation needs changing or something very special is happening at my end :) .

**Comment by thinklinux** [comment]
Same with me. I was debugging pretty much the whole day until I realised that it's because of eslint errors. It should be `false` by default. In most cases there is no reason the break a build because of couple of eslint warning/errors.

**Comment by edmorley** [comment]
I can't reproduce this using the latest version of eslint-loader and webpack 4.
Can you? If so, would you mind creating a reduced testcase? :-)

**Comment by ivandoric** [comment]
Maybe it has been changed since then. The issue was opened almost 5 months ago.
