### ISSUE TITLE
Console output verbosity

### ISSUE THREAD

**Issue by bf** [webpack-contrib/eslint-loader#226]
Is there a way to prevent `eslint-loader` from printing every warning to console.log, and only printing errors (if any?). I tried playing around with `emitOnWarning`, `emitOnError`, `failOnWarning` and `failOnError` options but it doesn't seem to work.

I want eslint-loader to only print to console when an error occured. Warnings are shown in the IDE and shouldn't pollute my webpack logs. 

Thank you!

**Comment by ricardogobbosouza** [comment]
@bf 
Use the option `quiet` to emit only errors
https://github.com/webpack-contrib/eslint-loader#quiet-default-false
