### ISSUE TITLE
ESLint loader breaks devtool options in webpack

### ISSUE THREAD

**Issue by marharyta** [webpack-contrib/eslint-loader#227]
After searching around a lot, I came to realization that eslint-loader in webpack breaks source map output.
If I use eslint in my webpack file as a loader for .js, this is the output that I get in chrome devtools when I make an error:
<img width="905" alt="screen shot 2018-05-01 at 16 54 31" src="https://user-images.githubusercontent.com/7344718/39488118-eb1dd600-4d89-11e8-8f3d-c63aa02eb975.png">
The error is shown in a bundles file.
My webpack config looks like this:
module: {
```
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          { loader: 'babel-loader' },
          {
            loader: 'eslint-loader',
            options: { formatter: require('eslint/lib/formatters/stylish') }
          }
        ]
      }
    ]
  },
```
If I delete eslint loader from the config, them my output in the console is correct and the error is shown in the right place:
<img width="1433" alt="screen shot 2018-05-01 at 18 04 42" src="https://user-images.githubusercontent.com/7344718/39488246-4a720c7a-4d8a-11e8-8d69-52c4180d4678.png">

My webpack config looks like:
```
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [{ loader: 'babel-loader' }]
      }
    ]
  },

```
I believe it is a bug, so this might need further investigation.
**I used:
"webpack": "^4.6.0",
"webpack-cli": "^2.0.13",
"webpack-dev-server": "^3.1.3"
"eslint": "^4.19.1",
 "eslint-config-prettier": "^2.9.0",
 "eslint-loader": "^2.0.0",
 "eslint-plugin-prettier": "^2.6.0",
 "eslint-plugin-react": "^7.7.0",**

**Chrome Version 66.0.3359.139 (Official Build) (64-bit)**

You can find more explanation of this error in a StackOverflow question here: [https://stackoverflow.com/questions/50105741/webpack-4-devtool-option-does-not-work-with-webpack-dev-server](https://stackoverflow.com/questions/50105741/webpack-4-devtool-option-does-not-work-with-webpack-dev-server)

and a description of my experience here:
[https://medium.com/p/79fb676417f4/edit](https://medium.com/p/79fb676417f4/edit)

**Comment by nothingismagick** [comment]
I can confirm a similar experience. Thanks for the detailed write-up! I have also noticed a very strange warning during a yarn install, not sure if it is related:

`warning " > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".`

**Comment by Mykybo** [comment]
I just run into this as well. This is pretty important, why are you ignoring this issue?
