### ISSUE TITLE
CLIEngine is not a constructor when using options.eslintPath

### ISSUE THREAD

**Issue by Mati365** [webpack-contrib/eslint-loader#229]
When I configure Webpack to load eslintrc.json from custom path I receive following error:
`ERROR in ./src/js/popup.js
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: eslint.CLIEngine is not a constructor`

my Webpack config:
`{
        enforce: 'pre',
        test: /\.js?$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: {
          eslintPath: path.join(__dirname, '../.eslintrc.json'),
        },
      },`

when I move file to root folder of project project compiles fine

**Comment by alesanchezr** [comment]
eslintPath is not a path to a file, it needs to be an instance of the eslint.CLIEngine.
https://eslint.org/docs/developer-guide/nodejs-api#cliengine

You would have to do something like:
```js
var CLIEngine = require("eslint").CLIEngine;

var cli = new CLIEngine({
    envs: ["browser", "mocha"],
    useEslintrc: false,
    rules: {
        semi: 2
    }
});`\
```

**Comment by nguyenthetoan** [comment]
+1 :worried:

**Comment by FabianoLothor** [comment]
+1

**Comment by yrue** [comment]
+1

**Comment by ricardogobbosouza** [comment]
Hi,
- [eslintPath](https://github.com/webpack-contrib/eslint-loader#eslintpath-default-eslint) path to eslint instance that will be used for linting.
- For the configuration file, use the `configFile` option
