### ISSUE TITLE
is it possible to generate a report into a specific path when using webpack-dev-server?

### ISSUE THREAD

**Issue by ThiagoFacchini** [webpack-contrib/eslint-loader#241]
Hi,

I have an use case where I would need to generate a report into a specific path while in dev mode.

**A bit of context**: When the rebuild ( from webpack-dev-server ) kicks in this report would be generated (in case of eslint errors), and picked by a 3rd party program which would thrown a desktop notification saying something may be wrong with the linting.

But, because webpack-dev-server writes the files to an in memory file system 'everything' that is generated while in dev mode goes to the same in memory file system which makes the report file invisible for this 3rd party watcher program, although available at e.g.: http://localhost:8080/eslint-report.xml (which is far from be ideal).

So my question is: How could I tell eslint-loader to write the report file into a specific path regardless  if the env is set to dev or prod?

I tried everything on the :
outputReport.filePath but since it is relative to webpack config: output.path I could achieve what I need.

Thanks in advance.

**Comment by MoOx** [comment]
I don't think webpack loader api could do that. You will need an express middleware plugged into webpack-dev-server.
