### ISSUE TITLE
Is there a way to specify what directory to look in for linting?

### ISSUE THREAD

**Issue by cssagogo** [webpack-contrib/eslint-loader#242]
I posted the following question on StackOverflow...
https://stackoverflow.com/questions/51392974/how-to-change-the-lint-directory-in-a-vue-js-app

Wasn't sure if there was something that could be done in exclude?  Maybe exclude everything that is not the directory I want?

exclude: !/src/vue-app,

**Comment by MoOx** [comment]
Sorry it's a webpack config question, not an issue. Hope you will find your way.
