### ISSUE TITLE
How can i enable colors ?

### ISSUE THREAD

**Issue by yanivkalfa** [webpack-contrib/eslint-loader#243]
When i run `eslint --color --quiet --cache --format=node_modules/eslint-formatter-pretty .` i get colored formatted warnings / errors.

How can i do the same with eslint-loader

**Comment by btimo** [comment]
@yanivkalfa can you share your project? sample?

**Comment by BulletAnt** [comment]
Did you try to add the --color option in the webpack command, like so : 
```bash
webpack --color
```
