### ISSUE TITLE
eslint-loader@2.1.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0"

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/eslint-loader#245]
using yarn to add specific dependencies for my project I get each time the following warning ... and need to reset dependencies on each update ...

 warning "@vue/cli-plugin-eslint > eslint-loader@2.1.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".

using webpack 4 , this should not be raised...

**Comment by MoOx** [comment]
We are not handling this kind of warning. Our definition seems fine according to npm docs. You should probably check yarn issues... https://github.com/yarnpkg/yarn/issues?utf8=✓&q=is%3Aissue+is%3Aopen+%22unmet+peer+dependency%22
