### ISSUE TITLE
Fixed:donesn't work  in 2.1.1 but works in 2.1.0

### ISSUE THREAD

**Issue by qqw78901** [webpack-contrib/eslint-loader#249]
like this https://github.com/webpack-contrib/eslint-loader/issues/248#issuecomment-424323066 to resolve this , I try to change the source code in 2.1.1

```js
  if (config.fix && (res.results[0].fixableErrorCount > 0 || res.results[0].fixableWarningCount)) {
      var eslint = require(config.eslintPath);
      eslint.CLIEngine.outputFixes(res);
    }
```
change to 
```js  
    if (config.fix && res.results[0].output) {
      var eslint = require(config.eslintPath);
      eslint.CLIEngine.outputFixes(res);
    }
```

it works. therefore it seems that this part of code has some problem.

![20180925203825](https://user-images.githubusercontent.com/15922193/46015386-c097bd80-c104-11e8-88d7-d5cfdc3d547f.png)

**Comment by MoOx** [comment]
Can you explain the rational behind this? What is inside `.output`?

**Comment by qqw78901** [comment]
I fonud the reason that `res.results[0].fixableErrorCount` and `res.results[0].fixableWarningCount` are wrong, which returned by the eslint-engine;
![loader](https://user-images.githubusercontent.com/15922193/46056046-625cf000-c181-11e8-807e-eb2bd5aeafc8.png)
And then, I enter `eslint/lib/engine`    fonud that the code in function  ``executeOnText`` (this function return wrong `fixableErrorCount` and `fixableWarningCount` )
``` js 
results.push(
                processText(
                    text,
                    configHelper,
                    resolvedFilename,
                    options.fix,
                    options.allowInlineConfig,
                    options.reportUnusedDisableDirectives,
                    this.linter
                )
            );
```

and finally found some wrong in function``processText``----
it calculate the count after fixed , so the `fixableErrorCount` and `fixableWarningCount` were calculated
after my code fixed;
my eslint version is `4.19.1`
Therefore, I think  it's better to no use ``fixableErrorCount`` to judge whether to fix or try another way to fixed this problem?  
 thank you all so much！

![cli-1](https://user-images.githubusercontent.com/15922193/46056126-b8ca2e80-c181-11e8-8b0f-64c20ae56987.png)
![cli](https://user-images.githubusercontent.com/15922193/46056125-b8ca2e80-c181-11e8-9424-da025011a1ed.png)

**Comment by layonez** [comment]
Can confirm that problem with "eslint": "5.6.0" also.

When there is fixable warnings/errors both `fixableErrorCount` and `fixableWarningCount` are 0. But `output` property is exists and should be used as flag to determine if fix needed.

```
res.results[0]= { 
  filePath: '/***/index.js',
  messages: [],
  errorCount: 0,
  warningCount: 0,
  fixableErrorCount: 0,
  fixableWarningCount: 0,
  **output**: 'import React, {Component} from \'react\';\nimport {withRouter, NavLink} from \'react-router- 
  dom\';\nimport PropTypes from \'prop-types\';\nimport.........
```

**Comment by wwjjltqq** [comment]
[CLIEngine](https://eslint.bootcss.com/docs/developer-guide/nodejs-api/#cliengine)

**fix** - This can be a boolean or a function which will be provided each linting message and should return a boolean. **True indicates that fixes should be included with the output report, and that errors and warnings should not be listed if they can be fixed**. However, the files on disk will not be changed. To persist changes to disk, call outputFixes().

**Comment by ElMassimo** [comment]
This bug was introduced in #244. In order to prevent loops, it should only write the file if there are __no more__ errors or warnings left:
```js
const result = res.results[0]
if (config.fix && result.output && result.errorCount === 0 && result.warningCount === 0) {
```
which will ensure that fixing works again, but prevent loops.

**Comment by waghcwb** [comment]
I can confirm this still a bug in `2.1.2` even after this PR https://github.com/webpack-contrib/eslint-loader/commit/d76372676b8badf57df3d6a22be5739d19e25637

---

I'm using `eslint-loader` with `nuxt@2.3.4`
