### ISSUE TITLE
Wrong errors on 2.1.1 that were not on 2.1.0

### ISSUE THREAD

**Issue by XavierLeTohic** [webpack-contrib/eslint-loader#251]
Since I updated to 2.1.1 I have new errors that should not appear and were not appearing on 2.1.0 :

<img width="520" alt="screen shot 2018-10-15 at 12 51 17" src="https://user-images.githubusercontent.com/6340490/46949411-45795580-d079-11e8-82a9-aac0ab88b233.png">

Here is the code, it doesn't work event with export default instead of module.exports : 

<img width="284" alt="screen shot 2018-10-15 at 12 54 08" src="https://user-images.githubusercontent.com/6340490/46949467-6c378c00-d079-11e8-948e-7710297f04e8.png">

The webpack aliases are been defined on `.eslintrc` as `'@': __dirname`

**Comment by ricardogobbosouza** [comment]
@XavierLeTohic 
Update to last version `v2.2.1`
