### ISSUE TITLE
Validate options passed to eslint-loader 

### ISSUE THREAD

**Issue by edmorley** [webpack-contrib/eslint-loader#252]
Hi!

Currently if eslint-loader is passed non-existent options, no error or warning is generated. 

This has tripped me up on multiple occasions, when I've accidentally used the wrong option name, or else forgotten to nest `baseConfig`-only options (such as `extends`) under `baseConfig` and instead incorrectly passed them as top-level options.

Whilst the eslint-loader docs mention that the eslint options are those passed to CLIEngine, the ESLint docs aren't overly clear, and there are some confusing footguns - such as:
* `globals` being an array when a top-level option, but an object when under `baseConfig`
* the environments option being called `envs` when top-level, but `env` when under `baseConfig` (plus also the different data type like `globals`)
* a small subset of settings not being available as top-level options and only under `baseConfig`

As such I think schema validation of the options passed to the loader would be useful. Other webpack loaders tend to use [schema-utils](https://www.npmjs.com/package/schema-utils) to do this.

Would there be any objection to a PR that adds support for this?
This would obviously be a breaking change (though version numbers are cheap).

**Comment by edmorley** [comment]
It looks like this would have also caught things like #173, where the reason their config didn't work, is because in that config `env` and `extends` needed to have been nested under `baseConfig` instead.

I've also filed an issue against ESLint for making CLIEngine validate its options (eslint/eslint#10272), however:
* that may never end up happening (and at the very least will take some time to get merged and released in the next major version)
* it won't help prevent eslint-loader being passed options that are technically valid for `CLIEngine` but that don't have any effect when using `executeOnText()` (for example `extensions`)
* it won't validate the type for eslint-loader specific options that are not passed to CLIEngine

**Comment by ricardogobbosouza** [comment]
Validating `eslint` options should be `eslint` responsibility, here in v3 we will validate the options for the loader
