### ISSUE TITLE
Update 'gotchas' documentation for NoErrorsPlugin

### ISSUE THREAD

**Issue by edmorley** [webpack-contrib/eslint-loader#256]
The readme [gotchas](https://github.com/webpack-contrib/eslint-loader#gotchas) section currently mentions that using `NoErrorsPlugin` results in no bundle output if eslint errors occurred in eslint-loader.

However:
* that plugin was replaced by [NoEmitOnErrorsPlugin](https://github.com/webpack/webpack/blob/v4.26.0/lib/NoEmitOnErrorsPlugin.js) 
* `NoEmitOnErrorsPlugin` is now automatically enabled in webpack 4, when `mode` is either unset, or set to `production`: 
  - https://github.com/webpack/webpack/blob/e1df721fd77634b5a22b4349c7d7ea15f0a2188e/lib/WebpackOptionsDefaulter.js#L267-L269
  - https://github.com/webpack/webpack/blob/3b6d1495c3858d59cfdb46b2343c07f2e4c1316d/lib/WebpackOptionsApply.js#L364-L366
* it appears that "So even ESLint warnings will fail the build. No matter what error settings are used for eslint-loader" reference is no longer true (since `emitWarning: true` worked, even with `--mode production`).

**Comment by dagadbm** [comment]
so how can I make eslint not break then?
