### ISSUE TITLE
webpack hmr: trying replace file to name-path with index... and fail

### ISSUE THREAD

**Issue by patriciussanctus** [webpack-contrib/eslint-loader#263]
hi! i am trying move file to encapsulated path, e.g `test.js` -> `test/index.js`
code of import:
```
import test from './test'
```

with webpack hot module replacement, eslint-loader shot error, but after restart it works.
please help, error by hmr:
```
ERROR in ./source/modules/test.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open '/Users/zzz/node/source/modules/test.js'
```

webpack: 4.12.2
eslint: 5.12.1
eslint-loader: ^2.1.1

**Comment by ricardogobbosouza** [comment]
Not a problem with `eslint-loader`, using only webpack the same error happens
