### ISSUE TITLE
LOOKING FOR A MAINTAINER

### ISSUE THREAD

**Issue by ThomasKientz** [webpack-contrib/eslint-loader#264]
From previous maintainer :

> Please please please, #webpack community, please take control on eslint-loader. Nobody is maintaining it. I do whatever I can because I don’t like to let things rot… but I am about to let it rot (I don’t use eslint-loader for months…) and will ignore its notifications soon.

https://twitter.com/MoOx/status/1044577532815855616

**Comment by MoOx** [comment]
@ThomasKientz stop acting like a consumer. You can maintain this package just by asking.

**Comment by ThomasKientz** [comment]
@MoOx I would love to but I have never maintained one before ! Please add me, I will see what can I do.

**Comment by MoOx** [comment]
Sadly I don’t have the right to add contributors since the package is under webpack .org.
Can @TheLarkInn or @ooflorent help us?
After that I could answer to your technical questions around the workflow to fix and release if necessary.

**Comment by evilebottnawi** [comment]
@MoOx i can help with permissions and rights

**Comment by evilebottnawi** [comment]
@ThomasKientz I can give you rights, except `npm`, we need to work with you for a while to avoid something illegal. I would also like to ask you how much time you can spend? Sometimes developers say what they will be maintain repo, but don't do this.

**Comment by ThomasKientz** [comment]
@evilebottnawi I would guess between 1 to 5 hours a week. But I am not sure that this repo needs this amount of time, right now (from what I understand) it needs to merge one pull request to fix an issue affecting a relatively large amont of people. To be clear I have never maintained an open source repo before but I would love to start contributing. I have 3 years of experience in web dev. 

@MoOx Would be very nice !

**Comment by evilebottnawi** [comment]
@ThomasKientz :+1: 
@MoOx ping me again (just make sure everything is right) and i will add rights to @ThomasKientz

**Comment by evilebottnawi** [comment]
@ThomasKientz invite was sent

**Comment by ThomasKientz** [comment]
@evilebottnawi thanks ! Will look into this tomorrow ;)

**Comment by MoOx** [comment]
Feel free to continue discussion here if you need anything.

**Comment by ThomasKientz** [comment]
@MoOx Can I merge https://github.com/webpack-contrib/eslint-loader/pull/262 directly or do I need to do something first ?

**Comment by ThomasKientz** [comment]
@MoOx https://github.com/webpack-contrib/eslint-loader/pull/262 seems ok and passed all tests.

But there is a review https://github.com/webpack-contrib/eslint-loader/pull/262#pullrequestreview-196512054. What is the best practice if I want to modify the pull request accordingly and avoid changes in `readme.md` ? Do I create a new commit by my side by copying only the desired changes (here : index.js) (thus spoiling credits of the author) ? 

Whom do I ask the npm rights ?

**Comment by ThomasKientz** [comment]
@MoOx Ready to push to npm ! https://github.com/webpack-contrib/eslint-loader/commit/02c1e76d9235823c6bb296ad68d74c99bfcc4445

**Comment by MoOx** [comment]
@ThomasKientz What is your npm login?

**Comment by ThomasKientz** [comment]
@MoOx blaydator

**Comment by MoOx** [comment]
@ThomasKientz You have been invited.

**Comment by MoOx** [comment]
Reopening as it seems that this package is clearly not maintained at this time.

**Comment by ricardogobbosouza** [comment]
@MoOx i can help with this.
This package does not need a lot of time, but attention when needed

**Comment by MoOx** [comment]
@evilebottnawi can you help us to add @ricardogobbosouza ?

**Comment by evilebottnawi** [comment]
Yes

@ricardogobbosouza  for releases ping me

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
I think we can release,
At least to have support for eslint 6

**Comment by evilebottnawi** [comment]
@ricardogobbosouza in todo, release will be tomorrow
