### ISSUE TITLE
errors not shown after starting webpack dev server after initial start

### ISSUE THREAD

**Issue by kelly-tock** [webpack-contrib/eslint-loader#267]
`node 11.12.0`
`webpack 4.8.2`
`webpack dev server 3.1.1`
`eslint-loader 2.1.2`

after doing a fresh install, and starting webpack dev server, the loader will properly display lint warnings/errors. I can go through and edit files to fix the issues, and when dev server refreshes, it shows the remaining issues. 

if I stop the dev server, then just start it, no warnings/errors are displayed, even though I know there still are some. 

```
{
        enforce: 'pre',
        test: /\.(ts|tsx)$/,
        include: [path.join(cwd, 'src/js')],
        loader: 'eslint-loader',
        options: {
          configFile: '.eslintrc.js',
          emitWarning: true,
          cache: false,
        },
      },
      {
        include: [path.join(cwd, 'src/js')],
        test: /\.(ts|tsx)$/,
        use: [
          {
            loader: 'cache-loader',
          },
          {
            loader: 'thread-loader',
            options: threadLoaderOptions,
          },
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              cacheCompression: false,
              babelrc: false,
             .....other stuff
            },
          },
        ],
      },
```

if I remove cache loader it displays all the time and this issue does not occur. 

is there a way to display the issues all the time while using cache loader?

**Comment by kelly-tock** [comment]
just to update, I also found that if I add
```
failOnWarning: true
```

this issue doesn't occur. however during development, i'm wanting it to still compile, and fix as I go. 

we have a pretty large project, so disabling cache loader doesn't seem to be an option for.

**Comment by kelly-tock** [comment]
any enabling of cacheing in the loader causes this issue as well. tried cache: true, and failOnWarning: true, but the issue persists.

**Comment by tmcdos** [comment]
Exactly the same situation here. Any chance to fix this?

**Comment by kelly-tock** [comment]
We ended up removing cache loader and turning on cacheing for eslint loader not as fast but ok for now

**Comment by hq5544** [comment]
The same.

**Comment by kelly-tock** [comment]
I found that if you make sure to enable root: true and what not from eslint to make sure it doesn't recursively check for eslint, that gave us a perf boost for sure.

**Comment by ricardogobbosouza** [comment]
@kelly-tock could you provide a repository ?

**Comment by barberdt** [comment]
@ricardogobbosouza @kelly-tock 

**Repro repository provided here:** https://github.com/barberdt/loader-issue

**Repro steps**:
```bash
```

**Comment by barberdt** [comment]
@ricardogobbosouza @kelly-tock

**Repro repository provided here:** https://github.com/barberdt/loader-issue

**Repro steps:**
```bash
$ git clone git@github.com:barberdt/loader-issue.git
$ cd loader-issue
$ yarn install
$ yarn run test
```

- Observe the output of the single eslint error:

```bash
ERROR in ./index.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/Users/davis/github/loader-issue/index.js
  1:13  error  'foo' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

ℹ ｢wdm｣: Failed to compile.
```

- Kill the dev server
- Start the dev server again (`yarn run test`)
- Observe a successful build instead of seeing the expected error.

Restarting the server from this point forward should continue to show a false successful build.

Without having dug into the issue itself, I'm not 100% sure which repo this issue belongs to between `eslint-loader`, `cache-loader`, `babel-loader`, `webpack`, and `webpack-dev-server`, but this was the most fleshed out of the related issues, so I thought I'd post here. Happy to move this repro around wherever needed.

**Comment by kelly-tock** [comment]
Thanks for providing this!

**Comment by ricardogobbosouza** [comment]
Hi @barberdt, @ kelly-tock
Thanks for reporting

I do not recommend using `cache-loader` and` eslint-loader` together, use the [`cache`](https://github.com/webpack-contrib/eslint-loader#cache) option

But if you want to use both together, enable the [`failOnError`](https://github.com/webpack-contrib/eslint-loader#failOnError) option.

Soon this loader will be deprecated in favor of this plugin [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)

**Comment by kelly-tock** [comment]
I am using typescript so recently switched raking over to be handled by fork ts checker plugin

**Comment by onebree** [comment]
@ricardogobbosouza Which loader exactly will be deprecated? Caching or ESLint? When will that deprecation happen, and is there a guide present for moving from one to the new plugin?

**Comment by ricardogobbosouza** [comment]
Hi @onebree 
- We are analyzing the depreciation of the `eslint-loader`
- We will be launching v1.0.0 of `eslint-webpack-plugin`  until this weekend

**Comment by ricardogobbosouza** [comment]
Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.
