### ISSUE TITLE
No Output Report in File when build fails under webpack 4

### ISSUE THREAD

**Issue by jo-te** [webpack-contrib/eslint-loader#268]
When eslint-loader ends webpack build with exit status 2 no outputReport will be written to specified file. Only with `emitWarning` set to true the outputReport will be written to file.
This seems to be an issue with webpack 4.+ since a downgrade to webpack@3.12.0 resolved this issue. 
I do not know if this concerns all webpack 4 versions but definitely the latest webpack 4 release (4.29.6).

**Comment by Valdermeyder** [comment]
I have experienced the same problem. Moreover, in my case, neither `emitWarning` nor `emitError` help. Versions I am using:
* webpack 4.29.6
* eslint-loader 2.1.2

**Comment by ricardogobbosouza** [comment]
@jo-te 
In v3 it will only be possible when using absolute path to `outputReport.filePath`
