### ISSUE TITLE
license problem

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/eslint-loader#277]
/cc @MoOx need update license, i can't work until we do this, example of license https://github.com/webpack-contrib/css-loader/blob/master/LICENSE

**Comment by MoOx** [comment]
that the exact same MIT license?
I am ok if you update it, you should just probably leave my name around as I am the initial creator of this module.

**Comment by evilebottnawi** [comment]
@MoOx 

> that the exact same MIT license?

yes

> I am ok if you update it, you should just probably leave my name around as I am the initial creator of this module.

Unfortunately I have no right to do it because it is a violation, only you can update license.

**Comment by MoOx** [comment]
what do you want me to add?

**Comment by evilebottnawi** [comment]
@MoOx send a PR with new license, link on license above

**Comment by MoOx** [comment]
Is this good for you https://github.com/webpack-contrib/eslint-loader/pull/278 ?

**Comment by evilebottnawi** [comment]
@MoOx not sure about we can leave you name in license, I asked this question to the person responsible for this question, i will ping you if something was wrong, anyway thanks for PR and feedback

**Comment by MoOx** [comment]
More details about this situation would be nice indeed. That the first time in my life I encounter this kind of "problem" :)

**Comment by ricardogobbosouza** [comment]
@MoOx I also do not know, but it is good to follow the default `Copyright JS Foundation and other contributors`, do not you think?

**Comment by MoOx** [comment]
This is not a big deal, I am just curious about the problem before doing anything blindly. I am no lawyer, but tons of projects have the original author in the mit license, I am curious why here it's an issue.

**Comment by MoOx** [comment]
I would add some background here:
I transferred this repo here (it was under my profile before) since I wasn't actually using the project, but was still maintaining it just enough so it didn't rot. @ooflorent asked me in DM to make the transfer. I wanted the community to have more control so I did it. But in practise nobody took control over the maintenance. The few PRs made was (from what I see) have been asked to sign a CLA & I have no idea why this is asked & no idea why there is an issue now. How many project don't waste time on things like that? What issue can this create? I am curious to know.

**Comment by evilebottnawi** [comment]
@MoOx before moving repo in `webpack-contrib` you need change license, i don't know why it was not done, but i can't work on project with invalid license in `webpack-contrib` (it is required by JS Foundation)

**Comment by MoOx** [comment]
Now you can do your stuff.
It's just very curious that you ask for a change without any explanation beside "it's requested by js foundation". At least a doc or something could help people to understand the reasons behind this.

**Comment by evilebottnawi** [comment]
@MoOx Honestly, I do not know can we `not accept`/`accept` the license with your name, I referred this question to the people responsible for it but apparently now they have no time for it, I am forbidden to work with a repository that does not contain right license in this organization. 

Sorry for that. I will write you here when i get answer and clarify, maybe we can return your name in license, sorry again

**Comment by MoOx** [comment]
Who is responsible for this request without any explicit explanation? I am curious as this doesn't make any sense :)
