### ISSUE TITLE
Support lint typescript file

### ISSUE THREAD

**Issue by hawx1993** [webpack-contrib/eslint-loader#279]
Can  `eslint-loader` support lint ts file and follow `eslintrc.json` while on webpack dev mode.

I wish we can lint ts file while use webpack to build, and we can check the lint error or warning while on dev mode, like `ForkTsCheckerWebpackPlugin`

**Comment by ricardogobbosouza** [comment]
@hawx1993 
I do not know if I understand...
Could you give me more details?

**Comment by hawx1993** [comment]
@ricardogobbosouza thanks for comment.
but it's occasional appearance, while I remove node_modules, and reinstall, sometimes it works, someTimes it doesn't work

**Comment by hawx1993** [comment]
@ricardogobbosouza not only in my computer, many of my colleagues have this problem.
