### ISSUE TITLE
Incorrect eslintPkgPath: `.../api.js/package.json`

### ISSUE THREAD

**Issue by rdhelms** [webpack-contrib/eslint-loader#282]
- Operating System: Mac OS
- Node Version: 10.15.1
- NPM Version: 6.4.1
- webpack Version: 4.28.4
- eslint-loader Version: 2.2.0

### Expected Behavior

Expecting regular Vue builds to succeed.

### Actual Behavior

See https://github.com/vuejs/vue-cli/issues/4231

Vue builds are failing due to an eslint-loader error.

### Code

[This addition](https://github.com/webpack-contrib/eslint-loader/commit/b6c3938aae61c0390ac8d941af50cf36df14cfc3#diff-168726dbe96b3ce427e7fedce31bb0bcR167) seems to result in `eslintPkgPath` sometimes adding `/package.json` to the path in situations where it should not:
```js
  var eslintPkgPath = "eslint/package.json";
  if (userEslintPath) {
    eslintPkgPath = userEslintPath + "/package.json";
  }

  var eslintVersion = require(eslintPkgPath).version;
```

### How Do We Reproduce?
See https://github.com/vuejs/vue-cli/issues/4231

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by genez** [comment]
could anybody post a workaround until we get the fix?
I am having this issue right now

**Comment by rdhelms** [comment]
There are some discussed workarounds in https://github.com/vuejs/vue-cli/issues/4231:
https://github.com/vuejs/vue-cli/issues/4231#issuecomment-508161533

There is also a proposed fix for vue-cli to use the directory rather than the file path:
https://github.com/vuejs/vue-cli/pull/4233

That PR should fix this issue for vue-cli cases, although I'm not sure if there are other instances where people may have been passing file paths to this module that would now be breaking.

**Comment by writebyheart** [comment]
I have this problem too.
And just comment like this then it work:smile:
```
  var eslintPkgPath = "eslint/package.json";
  //if (userEslintPath) {
  //  eslintPkgPath = userEslintPath + "/package.json";
  //}

  var eslintVersion = require(eslintPkgPath).version;
```

**Comment by evilebottnawi** [comment]
Somebody can test https://github.com/webpack-contrib/eslint-loader/pull/283?

**Comment by KnowledgeGarden** [comment]
I liked that patch. I just went in and replaced the require with '5.6.0' and it works fine, but that's not a fix. Perhaps that patch will get us back on the road.

**Comment by evilebottnawi** [comment]
Please tests https://github.com/webpack-contrib/eslint-loader/releases/tag/v2.2.1
