### ISSUE TITLE
First line of a file displays a weird colour

### ISSUE THREAD

**Issue by kud** [webpack-contrib/eslint-loader#292]
Hello!

I'm not sure if it's a bug or not, not sure if it depends on eslint-loader, eslint or my zsh/iterm2

but the first line of each file reported by eslint has a special colour, this is weird.

- Operating System: macOS 10.14.6
- Node Version: v12.9.0
- NPM Version: 6.11.2
- webpack Version: 4.39.2
- eslint-loader Version: 3.0.0

### Expected Behavior

No different colour?

### Actual Behavior

A colour for the first line:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/655838/63677962-77f1f400-c7ee-11e9-8b13-9c068f35116d.png">

**Comment by kud** [comment]
Thank you!

**Comment by ricardogobbosouza** [comment]
Resolved on eslint 6.3
