### ISSUE TITLE
eslint loader question

### ISSUE THREAD

**Issue by freeozyl80** [webpack-contrib/eslint-loader#293]
when i use eslint-loader and give custom config path, anything is ok unless i use eslint plugin, because eslint-loader generate the wrong context which has no eslint-plugin-xxx

graph is here
 --dirA // this is my webpack entry dir
     -- entry.js
 --dirB // this is my eslintrc 
     -- eslintrc.
     -- node_modules 
          -- eslint-plugin-xxx

i hope using eslint-loader , i can find eslint-plugin-xxx in dirB, however, webpack want find it in dirA ...

![image](https://user-images.githubusercontent.com/8967606/64923923-74f88b00-d811-11e9-84e2-ebb1da6b1d8d.png)

in addition, dirA and dirB has no same parent dir ...

Hope to get some advice -  =.=

**Comment by ricardogobbosouza** [comment]
@freeozyl80 
Please provide a repository with the issue.

**Comment by freeozyl80** [comment]
finally use process.chdir('xxxx') to resolve this Ques!  anyway, thanks
