### ISSUE TITLE
compile twice in `watchMode` with `options: { fix: true }`

### ISSUE THREAD

**Issue by iamolegga** [webpack-contrib/eslint-loader#303]
- Operating System: macOS Mojave 10.14.6 (18G95)
- Node Version: v12.9.1
- NPM Version: 6.10.2
- webpack Version: 4.41.0
- eslint-loader Version: ^3.0.2

### Expected Behavior

should not compile twice in `watchMode` with `options: { fix: true }`

### Actual Behavior

compile twice in `watchMode` with `options: { fix: true }`

### Code

https://github.com/iamolegga/eslint-loader-compile-twice-demo

### How Do We Reproduce?

https://github.com/iamolegga/eslint-loader-compile-twice-demo

**Comment by ricardogobbosouza** [comment]
Hi @iamolegga 
Thanks for reporting, sorry for the late reply

I followed the step by step, but I couldn't reproduce

**Comment by iamolegga** [comment]
Can you please provide logs of webpack?

**Comment by ricardogobbosouza** [comment]
```
Compilation  starting…


webpack is watching the files…


Compilation  finished

Hash: 92ff8cde8bef5080692c
Version: webpack 4.41.0
Time: 303ms
Built at: 2020-02-28 14:22:06
    Asset      Size  Chunks             Chunk Names
bundle.js  4.21 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./src/index.js] 57 bytes {main} [built]

Compilation  starting…


Compilation  finished
```

**Comment by iamolegga** [comment]
@ricardogobbosouza do you repeat this steps:

1. when webpack started clear console (cmd + K)
2. open src/index.js
3. remove quotes from object property and save

just tried again and got 2 builds as expected:

```sh
Compilation  starting…


Compilation  finished

Hash: 90a67c6e23dc77a6f06b
Version: webpack 4.41.0
Time: 42ms
Built at: 02/28/2020 9:34:57 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  4.2 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./src/index.js] 55 bytes {main} [built]

Compilation  starting…


Compilation  finished

Hash: 92ff8cde8bef5080692c
Version: webpack 4.41.0
Time: 18ms
Built at: 02/28/2020 9:34:58 PM
    Asset      Size  Chunks             Chunk Names
bundle.js  4.21 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./src/index.js] 57 bytes {main} [built]
```

This behaviour is explained (as I understand it) in same issue of another loader [here](https://github.com/iamolegga/prettier-loader/issues/1#issuecomment-335796706). Also there are more links in [last comment](https://github.com/iamolegga/prettier-loader/issues/1#issuecomment-537542770) to another loaders/plugins with same behaviour, maybe it could help

**Comment by ricardogobbosouza** [comment]
@iamolegga try to use [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)
And let me know if the error persists

**Comment by ricardogobbosouza** [comment]
Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.
