### ISSUE TITLE
Running webpack when the entry is using require.context does not fail with proper exit code

### ISSUE THREAD

**Issue by carlcodes** [webpack-contrib/eslint-loader#305]
The state of my application (migrating from angularjs to react) requires a need for requiring all files in a directory, as apposed to using normal imports / requires / react dom / whatever else. 
e.g. https://stackoverflow.com/questions/29421409/how-to-load-all-files-in-a-directory-using-webpack-without-require-statements

- Operating System: windows 10
- Node Version: 10.15.0
- NPM Version: 6.4.1
- webpack Version: 4.36.1
- eslint-loader Version: 3.0.2

### Expected Behavior

When using `require.context` to require files, running `yarn webpack` should fail with exit code 2 if there are eslint errors.

### Actual Behavior

the script shows the eslint errors but does not fail.

https://github.com/carlcodes/testcase-eslint-loader-requireAll

### How Do We Reproduce?

pull down my above project, run `yarn`, run `yarn webpack`. if you toggle the commented out code in the entry file it works, but my setup needs it to work as is.

**Comment by ricardogobbosouza** [comment]
Hi @carlcodes 
Please, use [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)
We are building this plugin to have more control than the loader
