### ISSUE TITLE
TypeError: CLIEngine is not a constructor

### ISSUE THREAD

**Issue by PantongWu** [webpack-contrib/eslint-loader#309]
- Operating System:  Mac 10.15.1
- Node Version: 12.12
- Yarn Version: 1.19.1
- webpack Version: 4.41.2
- eslint-loader Version :3.0.2

我不清楚是哪里chu出了问题
![image](https://user-images.githubusercontent.com/21765389/69773219-2c742b00-11cd-11ea-8486-d75cb4f9de97.png)

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by ricardogobbosouza** [comment]
Hi @PantongWu 
What version of eslint?
