### ISSUE TITLE
Different lint results between webpack and cli

### ISSUE THREAD

**Issue by simkessy** [webpack-contrib/eslint-loader#313]
I'm getting Linting Errors when I run: 

> webpack --config ./webpack.dev.config.js

I get multiple liniting errors. 

However, I've run in the terminal this command to clean up my files: 

> prettier --write '**/{*.js,*.jsx,*.css,*.scss}' && yarn run eslint --fix 'src/**'

This went through and updated 90+ files in my repository. I'm not entirely sure why I'd get any linting errors following this. 

This is my webpack config: 

      module: {
        rules: [
          {
            // will compile both js and jsx files
            // 'pre' will make sure it checks linting before it's compiled
            enforce: 'pre',
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'eslint-loader',
            options: {
              // configFile: path.resolve('./.eslintrc'),
              cache: true,
              // fix: true, -- this will change source
              emitWarning: false,
              emitErrors: true,
              failOnError: false,
              quiet: true
            }
          },
          {
            enforce: 'pre',
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            loader: 'babel-loader'
          }
        }
     }

I'm suspecting their using different configs? 

These are some related dependencies I have: 

      "devDependencies": {
        "@babel/cli": "^7.7.5",
        "@babel/core": "^7.7.5",
        "@babel/plugin-proposal-object-rest-spread": "^7.7.4",
        "@babel/polyfill": "^7.7.0",
        "@babel/preset-env": "^7.7.5",
        "@babel/preset-flow": "^7.7.4",
        "@babel/preset-react": "^7.7.4",
        "babel-eslint": "^10.0.3",
        "babel-jest": "^24.9.0",
        "enzyme": "^3.2.0",
        "enzyme-to-json": "^3.3.0",
        "eslint": "^6.7.2",
        "eslint-import-resolver-webpack": "^0.12.0",
        "eslint-loader": "^3.0.3",
        "eslint-plugin-flowtype": "^4.5.2",
        "eslint-plugin-import": "^2.19.1",
        "eslint-plugin-jest": "^23.1.1",
        "eslint-plugin-jsx-a11y": "^6.2.3",
        "eslint-plugin-prettier": "^3.1.1",
        "eslint-plugin-react": "^7.17.0",
        "eslint-config-airbnb": "^18.0.1",
        "eslint-plugin-react-hooks": "^1.7.0",
        "flow-bin": "^0.78.0",
        "jest": "^24.9.0",
        "jest-cli": "^24.9.0",
        "jest-matchers": "^20.0.3",
        "mini-css-extract-plugin": "^0.8.0",
        "prettier": "^1.19.1",
        "react-hot-loader": "^1.3.1",
        "react-test-renderer": "16.8",
        "terser-webpack-plugin": "^2.2.2",
        "webpack-dev-server": "^3.9.0"
      }

**Comment by eacdev** [comment]
How did you fix this?
