### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by linlinyang** [webpack-contrib/eslint-loader#318]
- Operating System: window10
- Node Version: v12.13.0
- NPM Version:6.12.0
- webpack Version: 4.41.5
- eslint-loader Version: 3.0.3

### Expected Behavior

run well,no warning

### Actual Behavior

WARNING in ./src/lang/index.js
Module Warning (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):
Cannot read property 'range' of null
Occurred while linting D:\开发项目\gisaid_desktop_fe\src\lang\index.js:19
 @ ./src/index.js 131:0-31 146:8-12

**Comment by ricardogobbosouza** [comment]
@linlinyang  Please provide a repository with the issue.

**Comment by linlinyang** [comment]
@ricardogobbosouza Maby this is babel-loader version problem

**Comment by ricardogobbosouza** [comment]
Closing because it is not a problem with eslint-loader
