### ISSUE TITLE
Eslint-loader is not using .eslintrc.js configuration

### ISSUE THREAD

**Issue by eacdev** [webpack-contrib/eslint-loader#324]
- Operating System: Linux
- Node Version: 13.9
- NPM Version: 6.13.7
- webpack Version: 4.43
- eslint-loader Version: ^3.0.0

### Expected Behavior

Eslint-loader should use the configuration specified in .eslintrc.js.

### Actual Behavior

Eslint-loader uses a unknown set of default rules. The result is that I am getting only 6 errors with eslint-loader whereas if I run eslint directly (node_modules/.bin/eslint "./client/**/*" I get ~30 errors.

Same as: https://github.com/webpack-contrib/eslint-loader/issues/269 maybe. Unfortunately removing node_modules did not solve the issue.

### Code
**webpack.config.js**
```js
{
    test: /\.ts$/,
    enforce: 'pre',
    loader: 'eslint-loader',
    options: {
        configFile: './client/.eslintrc.js'
    }
}, {
    test: /\.ts$/,
    exclude: '/node_modules/',
    loader: 'babel-loader',
    options: {
        presets: ['@babel/preset-env', '@babel/preset-typescript'],
        plugins: [
            ['@babel/plugin-proposal-decorators', {
                legacy: true
            }],
            ['@babel/plugin-proposal-class-properties', {
                loose: true
            }],
            ['@babel/plugin-transform-runtime', {
                regenerator: true
            }],
            ['@babel/plugin-transform-typescript']
        ]
    }
}
```
**.eslintrc.js**

```js
module.exports = {
  root: true,
  parser: 'vue-eslint-parser',
  ignorePatterns: ['webpack.config.js'],
  parserOptions: {
    parser: '@typescript-eslint/parser'
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/essential',
    'plugin:prettier/recommended'
  ]
};
```

### How Do We Reproduce?

Clone this repo. to reproduce: https://github.com/eacdev/vue-webpack-custom-config

Run "npm run start:client" and compare to "node_modules/.bin/eslint .client/**/\**"

**Comment by ricardogobbosouza** [comment]
@eacdev 
We use official eslint api, maybe something wrong in configuration or setup
