### ISSUE TITLE
failOnError option doesn't work with ts-loader and webpack-dev-server

### ISSUE THREAD

**Issue by pvcresin** [webpack-contrib/eslint-loader#327]
https://stackoverflow.com/questions/61617087/eslint-loader-failonerror-option-doesnt-work-with-ts-loader-and-webpack-dev-ser

I'm not sure this problem is with the eslint-loader.
Let me know if I'm wrong.

- Operating System: macOS Catalina v10.15.4
- Node Version: 12.16.2
- NPM Version: 6.14.4
- webpack Version: 4.33.0
- eslint-loader Version: 4.0.2

**Comment by ricardogobbosouza** [comment]
Hi @pvcresin 
I can't reproduce your problem

**Comment by ricardogobbosouza** [comment]
Hi @pvcresin 
Try to use [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)

**Comment by pvcresin** [comment]
@ricardogobbosouza I'll give it a shot.

**Comment by pvcresin** [comment]
@ricardogobbosouza 
I've tried it, but it doesn't work. https://github.com/pvcresin/eslint-webpack-error
I'm getting an error in webpack.config.js.
```sh
yarn start
yarn run v1.22.4
$ webpack-dev-server --mode development
✖ ｢wdm｣:  [ESLintError: 
/Users/pvcresin/Desktop/eslint-plugin-error/webpack.config.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: webpack.config.js.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)
] {
  name: 'ESLintError'
}
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
```
I found an issue with a similar error, but it wasn't very helpful. https://github.com/typescript-eslint/typescript-eslint/issues/864

**Comment by ricardogobbosouza** [comment]
@pvcresin set extensions:
```js
new ESLintPlugin({
  extensions: ['ts', 'tsx'],
  failOnError: true,
})
```

**Comment by pvcresin** [comment]
@ricardogobbosouza Thank you. The correct error was obtained!

```sh
$ webpack-dev-server --mode development
✖ ｢wdm｣:  [ESLintError: 
/Users/pvcresin/.Trash/eslint-plugin-error/src/main.ts
  1:7  error  'a' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
] {
  name: 'ESLintError'
}
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
```

What is this, by the way?
`name: 'ESLintError'`
name: 'ESLintError'

**Comment by ricardogobbosouza** [comment]
See https://github.com/webpack-contrib/eslint-webpack-plugin#failonerror

**Comment by pvcresin** [comment]
@ricardogobbosouza 
Am I using failOnError incorrectly? https://github.com/pvcresin/eslint-webpack-error
Does failOnError mean that once it fails, I have to redo the build?
Does that mean I can't check for ESLint errors every time I save a file?

**Comment by pvcresin** [comment]
@ricardogobbosouza I totally get it. It works!!
```js
    new ESLintPlugin({
      extensions: ['ts', 'tsx'],
      // failOnError: true,
    }),
```
