### ISSUE TITLE
eslint-plugin-import fails to load properties with eslint-loader but works with stand alone eslint

### ISSUE THREAD

**Issue by liesislukas** [webpack-contrib/eslint-loader#329]
- Operating System: 
![image](https://user-images.githubusercontent.com/2733862/82325980-cd0d1000-99e4-11ea-97f4-ea346c21d89c.png)

- Node Version:
- NPM Version:
![image](https://user-images.githubusercontent.com/2733862/82326004-d5fde180-99e4-11ea-850c-e29ad58b7659.png)

(using through react-scripts 3.2.0)

- webpack Version: 4.41.0
- eslint-loader Version: 3.0.2

I'm trying to use `import/order` eslint rule and it does have some custom properties yet eslint-loader does not recognize those and throws an error if I try to use properties with the rule. When i use eslint from the command line it does work, it also works fine in webstorm.

`"eslint-plugin-import": "^2.20.2",`
https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/order.md

```
'import/order': ['warn', {
      alphabetize: {order: 'asc', caseInsensitive: true},
    }],
```

**Comment by ricardogobbosouza** [comment]
Hi @liesislukas 

Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.

Related #328
