### ISSUE TITLE
 Parsing error: Unexpected token ..

### ISSUE THREAD

**Issue by akvaliya** [webpack-contrib/eslint-loader#330]
- Operating System:
- Node Version: v12.16.2
- NPM Version: 6.14.4
- webpack Version: ^4.42.1
- eslint-loader Version: ^4.0.2

### Expected Behavior

It should be able to parse

### Actual Behavior
Parsing error: Unexpected token ..
![](https://content.screencast.com/users/jalpeshrajani/folders/Jing/media/810114af-2225-4e33-b545-c09017f9b9bf/2020-05-22_1335.png)

### Code
```js
// webpack.config.js
{
    test: /\.js$/,
    exclude: /node_modules/,
    loader: 'eslint-loader',
    include: path.resolve(__dirname, 'app'),
    options: {
        failOnError: true,
    },
},
```

```js
Object.entries(data).flatMap(([key,v])=>v.map(x=>({key, ...x})))
```

### How Do We Reproduce?

`Object.entries(data).flatMap(([key,v])=>v.map(x=>({key, ...x})))`
 
... syntax works with array but not like above. What am i missing here?

**Comment by ricardogobbosouza** [comment]
Hi @akvaliya 
I couldn't reproduce

Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.
