### ISSUE TITLE
Plugin "import" was conflicted

### ISSUE THREAD

**Issue by yoyo837** [webpack-contrib/eslint-loader#333]
- Operating System: MacOS 10.15.5(19F101)
- Node Version: v12.18.1
- NPM Version: v6.14.5
- webpack Version: v4.43.0
- eslint-loader Version: v4.0.2

### Actual Behavior
```
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Plugin "import" was conflicted between "src/commons/.eslintrc.js » eslint-config-standard" and ".eslintrc.js".
```

`src/commons/` is a git submodule.

**Comment by rodrigogs** [comment]
Having the same issue in a mono repo. How can I work with different eslint configs inside the same repo? Is it possible?

**Comment by rodrigogs** [comment]
Solved it by using `root: true` in my eslintrc.js
