### ISSUE TITLE
eslint-laoder failing the build even if the failOnError set to false

### ISSUE THREAD

**Issue by vikas-bansal-DisneyPH** [webpack-contrib/eslint-loader#334]
- Operating System: OSX 10.15
- Node Version: 10.21.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- eslint-webpack-plugin Version: 4.0.2

### Expected Behavior

Build should be successful even if there are linting errors if set `failOnError` to false

### Actual Behavior

even if I have set the failOnError to false build is failing if there is even a single linting error.

### Code

```
const path = require("path");
module.exports = env => {
  return {
    entry: path.join(__dirname, "src/js/server.js"),
    output: {
      path: path.resolve(__dirname),
      publicPath: "/",
      filename: "server.bundle.js"
    },

    target: 'node',

    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: ["babel-loader",
            {
              loader: 'eslint-loader',
              options: {
                fix: false,
                emitWarning: false,
                emitError: false,
                failOnError: false,
                failOnWarning: false,
                quiet: true,
              }
            }
          ]
        }
      ]
    }
  };
};
```

<img width="730" alt="Screenshot 2020-06-25 at 11 06 11 PM" src="https://user-images.githubusercontent.com/66246267/85771316-6c869680-b739-11ea-860f-749e4e0087e5.png">

**Comment by cactusjosh** [comment]
I have this problem too. Did you manage to fix it okay?

**Comment by ricardogobbosouza** [comment]
Hi @vikas-bansal-DisneyPH 

Please use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/eslint-webpack-plugin). `eslint-loader` will be deprecated.
