### ISSUE TITLE
Deprecate eslint-loader

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-loader#337]
Use [`eslint-webpack-plugin`](https://github.com/webpack-contrib/) instead of `eslint-loader`

See https://github.com/webpack-contrib/eslint-webpack-plugin#about-plugin

**Comment by millerrafi** [comment]
Should this be noted [in the docs](https://webpack.js.org/loaders/eslint-loader/)?

**Comment by evilebottnawi** [comment]
@ricardogobbosouza I think it is time to deprecated, webpack@5 eta is `2020-10-10`, so I think we can do it

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
I'll do it tomorrow =)

**Comment by ricardogobbosouza** [comment]
@evilebottnawi deprecated
https://www.npmjs.com/package/eslint-loader
