### ISSUE TITLE
Reload .eslintrc when it's changed

### ISSUE THREAD

**Issue by dashed** [webpack-contrib/eslint-loader#43]
Minor nitpick. 

When using webpack with `watch: true`, and editing `.eslintrc`, I'd have to restart webpack for the new `.eslintrc` changes to take effect.

**Comment by frontsideair** [comment]
I'd like to see that too.

**Comment by MoOx** [comment]
PR are always welcome

**Comment by slightlytyler** [comment]
Have also run into an issue where I need similar functionality to accommodate https://github.com/apollographql/eslint-plugin-graphql. In my case I need to force eslint-loader to reload .eslintrc on *every* build. I see #151 and am wondering which of the cases described in this issue are satisfied by it. If my case is not covered I'll gladly contribute to that PR or another

**Comment by wrakky** [comment]
#151 still requires webpack to be restarted when changes are made to the rules so doesn't address this issue.

It also needs to be considered that there could be multiple .eslintrc files located anywhere in the project (see #123 and `configFile` option) and rules could also be applied directly to the eslint-loader options.

**Comment by sudo-suhas** [comment]
@MoOx I would like to work on this. Could you please help me figure out the approach?

**Comment by MoOx** [comment]
I guess you should somehow watch for the file being used, and reload it in memory. Nothing is made to support this so you will need to handle this from scratch I guess.

**Comment by sudo-suhas** [comment]
With eslint, there may not be just one eslint config file right? Would also need to invalidate cache when the config is modified.

**Comment by MoOx** [comment]
I guess so. Not an easy problem to solve and might open up to lots of bugs. Not sure if that's a good idea. If you work on your config, you should probably more play with eslint cli & files directly.

**Comment by sudo-suhas** [comment]
This is what I have so far. 
- Get the eslint config files using [`globby`](https://github.com/sindresorhus/globby) and the pattern `["**/.eslintrc.*", "package.json", "!node_modules/**/*"]`.
- Hash these files using [`hash-files`](https://www.npmjs.com/package/hash-files) and use it as part of the `cacheIdentifier`. However, this module is a little broken as the glob file resolution does not work correctly(hence the need for `globby`). Maybe I could use [`hasha`]() instead.

However, this isn't enough as the `eslint.CLIEngine` seems to cache the config as well. How do you suggest I handle this?

**Comment by sudo-suhas** [comment]
@MoOx Could you please help me out a little?

**Comment by langri-sha** [comment]
Worth considering is that ESLint can also be configured via `package.json`. See [Using Configuration Files](https://eslint.org/docs/user-guide/configuring#using-configuration-files).

**Comment by MoOx** [comment]
@sudo-suhas sorry I don't know where to start with this. The codebase is pretty small so you should try to understand it, check automated tests and see how you can tackle the problem. Feel free to ask questions if you need some detailed informations about a specific problem/ piece of code.

**Comment by ricardogobbosouza** [comment]
Use `nodemon` for this.
Ex: `nodemon --watch .eslintrc.js --exec webpack`

**Comment by DanielSchaffer** [comment]
@ricardogobbosouza that's not ideal - you lose all the benefits you get from running Webpack in watch mode
